config/routes.rb
Rails.application.routes.draw do
  resources :cruises do
      member do
        get :aspect, to: 'observations#aspect'
      end
    resources :observations, except: [:new], shallow: true do
      collection do
        
        post :import
        post :import_follow_up
        delete :all
        delete :unapproved
        delete :invalid
      end
      member do
        patch :approve
      end
      
      resources :photos, shallow: false
      resources :comments, except: [:index, :show], shallow: false
    end
    resources :charts, only: [:index] do
      get :total_concentration, on: :collection
      get :ice_type, on: :collection
    end
    post :approve, on: :member
    post :approve_observations, on: :member
    resources :uploaded_files, only: [:create, :new]
    resources :photos, only: [:index] do
      get :download
    end
  end
  resources :lookups, only: [:index, :show]

  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  get '/auth/:provider/disable', to: 'users#disable_provider'
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  resources :sessions
  resources :memberships
  get '/photos/*filename', to: 'photos#show', as: :photos

  resources :users

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'cruises#index'

end

app/models/lookup.rb
class Lookup < ActiveRecord::Base
  validates_presence_of :code, :name
  validates_uniqueness_of :code, scope: :type

  def code
    super.send(code_datatype)
  end

  def code_with_name
    "#{code} :: #{name}"
  end

  def code_datatype
    :to_i
  end
end

app/controllers/lookups_controller.rb
class LookupsController < ApplicationController
  before_action :set_lookup, only: [:show, :edit, :update, :destroy]

  # GET /lookups
  # GET /lookups.json
  def index
    @lookups = Lookup.all
  end

  # GET /lookups/1
  # GET /lookups/1.json
  def show
  end

  # GET /lookups/new
  def new
    @lookup = Lookup.new
  end

  # GET /lookups/1/edit
  def edit
  end

  # POST /lookups
  # POST /lookups.json
  def create
    @lookup = Lookup.new(lookup_params)

    respond_to do |format|
      if @lookup.save
        format.html { redirect_to @lookup, notice: 'Lookup was successfully created.' }
        format.json { render :show, status: :created, location: @lookup }
      else
        format.html { render :new }
        format.json { render json: @lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lookups/1
  # PATCH/PUT /lookups/1.json
  def update
    respond_to do |format|
      if @lookup.update(lookup_params)
        format.html { redirect_to @lookup, notice: 'Lookup was successfully updated.' }
        format.json { render :show, status: :ok, location: @lookup }
      else
        format.html { render :edit }
        format.json { render json: @lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lookups/1
  # DELETE /lookups/1.json
  def destroy
    @lookup.destroy
    respond_to do |format|
      format.html { redirect_to lookups_url, notice: 'Lookup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lookup
    @lookup = Lookup.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def lookup_params
    params.require(:lookup).permit(:code, :name, :type, :comment)
  end
end

app/helpers/lookups_helper.rb
module LookupsHelper

  def sort_by_code(lookups)
    lookups.sort_by { |l| l.code.to_i }
  end

end

app/views/lookups/_form.html.haml
= form_for(@lookup) do |f|
  - if @lookup.errors.any?
    #error_explanation
      %h2
        = pluralize(@lookup.errors.count, "error")
        prohibited this lookup from being saved:
      %ul
        - @lookup.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :code
    %br/
    = f.number_field :code
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :type
    %br/
    = f.text_field :type
  .field
    = f.label :comment
    %br/
    = f.text_field :comment
  .actions
    = f.submit

app/views/lookups/edit.html.haml
%h1 Editing lookup
= render 'form'
= link_to 'Show', @lookup
|
\#{link_to 'Back', lookups_path}

app/views/lookups/index.html.haml
%h1 Listing lookups
%table
  %thead
    %tr
      %th Code
      %th Name
      %th Type
      %th Comment
      %th{:colspan => "3"}
  %tbody
    - @lookups.each do |lookup|
      %tr
        %td= lookup.code
        %td= lookup.name
        %td= lookup.type
        %td= lookup.comment

app/views/lookups/new.html.haml
%h1 New lookup
= render 'form'
= link_to 'Back', lookups_path

app/views/lookups/show.html.haml
%p#notice= notice
%p
  %strong Code:
  = @lookup.code
%p
  %strong Name:
  = @lookup.name
%p
  %strong Type:
  = @lookup.type
%p
  %strong Comment:
  = @lookup.comment