config/routes.rb
Rails.application.routes.draw do
  resources :cruises do
      member do
        get :aspect, to: 'observations#aspect'
      end
    resources :observations, except: [:new], shallow: true do
      collection do
        
        post :import
        post :import_follow_up
        delete :all
        delete :unapproved
        delete :invalid
      end
      member do
        patch :approve
      end
      
      resources :photos, shallow: false
      resources :comments, except: [:index, :show], shallow: false
    end
    resources :charts, only: [:index] do
      get :total_concentration, on: :collection
      get :ice_type, on: :collection
    end
    post :approve, on: :member
    post :approve_observations, on: :member
    resources :uploaded_files, only: [:create, :new]
    resources :photos, only: [:index] do
      get :download
    end
  end
  resources :lookups, only: [:index, :show]

  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  get '/auth/:provider/disable', to: 'users#disable_provider'
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  resources :sessions
  resources :memberships
  get '/photos/*filename', to: 'photos#show', as: :photos

  resources :users

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'cruises#index'

end

app/models/concerns/importable/observation.rb
module Importable
  module Observation
    extend ActiveSupport::Concern

    ASSIGNABLE_ATTRIBUTES = %w( observed_at latitude longitude uuid
                                primary_observer_id_or_name
                                additional_observers_id_or_name).freeze

    ASSIGNABLE_MODELS = %w( ice ice_observations meteorology notes comments ship photos).freeze

    def from_export(json)
      obs_data = json.dup

      scrub_existing_data
      rewrite_legacy_observed_at(obs_data)
      rewrite_observers(obs_data, 'primary_observer')
      rewrite_observers(obs_data, 'additional_observers')

      assign_attributes(obs_data.select { |k, _v| ASSIGNABLE_ATTRIBUTES.include?(k) })

      ASSIGNABLE_MODELS.each do |model|
        next unless obs_data.key?(model)
        case
        when obs_data[model].is_a?(Hash)
          send("build_#{model}").from_export(obs_data[model])
        when obs_data[model].is_a?(Array)
          obs_data[model].each do |m|
            send(model).build.from_export(m)
          end
        end
      end

      self
    end

    def rewrite_legacy_observed_at(json)
      json['observed_at'] = json.delete('obs_datetime') if json.key?('obs_datetime')
    end

    def rewrite_observers(json, key)
      json["#{key}_id_or_name"] = json.delete(key) if json.key?(key)
    end

    def scrub_existing_data
      self.status = 'saved'
      (ASSIGNABLE_MODELS - ['photos']).each do |model|
        send(model).try(:destroy)
        send(model).try(:destroy_all)
      end
      (ASSIGNABLE_ATTRIBUTES).each do |attribute|
        send("#{attribute}=", nil)
      end
    end
  end
end

app/controllers/observations_controller.rb
require "rubypython"
class ObservationsController < ApplicationController
  authorize_resource except: [:aspect]

  before_action :set_observation, only: [:show, :edit, :update, :destroy]

  # GET /observations
  # GET /observations.json
  def index
    @cruise = Cruise.find(params[:cruise_id])
    @observations = @cruise.observations.order(observed_at: :desc).accessible_by(current_ability)
    
    
    
    respond_to do |format|
      format.csv { send_data build_csv, filename: "observations-#{@cruise.id}.csv"}
      format.json { send_data build_json, filename: "observations-#{@cruise.id}.json"}
      format.geojson { send_data build_geojson, filename: "observations-#{@cruise.id}.geojson"}
      format.sigrid3
    end
  end

  def aspect

    @cruise = Cruise.find(params[:id])
    @observations = @cruise.observations.order(observed_at: :desc).accessible_by(current_ability)
    
    RubyPython.start(:python_exe => "python2.7") # start the Python interpreter
    
    a2a =  RubyPython.import("a2a")
    
    assist = build_csv
    Rails.logger.info(assist)
    data = a2a.assist2aspect.str2str(assist)

    respond_to do |format|
      format.csv { send_data data, filename: "aspect-observations-#{@cruise.id}.csv"}
    end

    RubyPython.stop # stop the Python interpreter
    
  end

  # GET /observations/1
  # GET /observations/1.json
  def show
  end

  # # GET /observations/new
  # def new
  #   @cruise = Cruise.find(params[:cruise_id])
  #   @observation = @cruise.build_observation
  # end

  # GET /observations/1/edit
  def edit
    @observation.valid?
    @observation.faunas.build
    @observation.photos.build
  end

  # POST /observations
  # POST /observations.json
  def create
    @cruise = Cruise.find(params[:cruise_id])
    @observation = @cruise.build_observation

    respond_to do |format|
      if @observation.save validate: false
        format.html { redirect_to edit_observation_path(@observation), notice: 'Observation was successfully created.' }
        format.json { render :show, status: :created, location: @observation }
      else
        format.html { render :new }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /observations/1
  # PATCH/PUT /observations/1.json
  def update
    @observation.assign_attributes observation_params
    respond_to do |format|
      if @observation.save(validate: false)
        if params[:commit] == 'Save and Exit'
          format.html { redirect_to root_url }
        else
          format.html { redirect_to edit_observation_path(@observation), notice: 'Observation was successfully updated.' }
        end
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /observations/1
  # DELETE /observations/1.json
  def destroy
    @observation.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Observation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    @cruise = Cruise.find params[:cruise_id]

    @csv_observation = CsvObservation.new(import_params)

    respond_to do |format|
      if @csv_observation.errors.any?
        format.json { render json: @csv_observation.errors.full_messages, status: :unprocessable_entity }
      else
        @observation = @csv_observation.build_observation
        @observation.cruise = @cruise
        if @observation.save validate: false
          format.html { redirect_to cruises_url, notice: 'Observations were successfully imported' }
          format.json { head :no_content }
          format.js
          AdminMailer.new_csv_upload(@observation)
        else
          format.html { redirect_to cruises_url, notice: 'There was an error importing the observations' }
          format.json { render json: @observation.errors.full_messages, status: :unprocessable_entity }
        end
      end
    end
  end
  
  def import_follow_up
    # send mail after import is finised
    @cruise = Cruise.find params[:cruise_id]
    AdminMailer.new_csv_upload(@cruise).deliver
    render :nothing => true
  end

  def all
    @cruise = Cruise.find params[:cruise_id]

    @cruise.observations.destroy_all
    respond_to do |format|
      if assist?
        format.html { redirect_to root_url, notice: 'All observations were successfully destoyed.' }
      else
        format.html { redirect_to cruise_url(@cruise), notice: 'All observations were successfully destroyed.' }
      end
    end
  end

  def unapproved
    @cruise = Cruise.find params[:cruise_id]

    @cruise.observations.saved.destroy_all
    respond_to do |format|
      format.html { redirect_to cruise_url(@cruise), notice: 'All unapproved observations were successfully destroyed.' }
    end
  end

  def invalid
    @cruise = Cruise.find params[:cruise_id]
    @observations = @cruise.observations.reject(&:valid?)
    Observation.where(id: @observations).destroy_all

    respond_to do |format|
      format.html { redirect_to cruise_url(@cruise), notice: 'All unapproved observations were successfully destroyed.' }
    end
  end

  def approve
    @observation = Observation.find params[:id]

    if @observation.valid?
      @observation.accept!
    else
      flash[:error] = "Unable to approve an invalid observation"
    end

    redirect_to cruise_path(@observation.cruise)
  end

private

  def build_csv
    ## build csv observation file
    template = "<%= Observation.csv_headers %>
    <% @observations.each do |obs| %><%= obs.as_csv.to_csv.chomp.html_safe %>
    <% end %>
    "
    csv = ERB.new(template).result binding
  end
  
  def concentration_color(dominant_ice_type)
    case dominant_ice_type
    when 'old' then '#50BBD4'
    when 'new' then '#D9D9D9'
    when 'first_year' then '#BFD7D3'
    when 'other' then '#92A9C4'
    else '#FF0000'
    end
  end

  
  def build_geojson
    result = Jbuilder.new do |json|
      json.type 'FeatureCollection'
      json.features do
        json.array @observations do |observation|
          json.type 'Feature'
          json.geometry do
            json.type 'Point'
            json.coordinates [observation.longitude, observation.latitude]
          end
          json.properties do
            json.iceConcentration observation.ice.total_concentration
            json.fillColor concentration_color(observation.dominant_ice_type)
            json.dominantIceType observation.dominant_ice_type
          end
        end
      end
    end.attributes!
    JSON.generate(result)
  end 
  
  def build_json
    ## build json observation file
    result = Jbuilder.new do |json|
        json.extract! @cruise, :starts_at, :ends_at, :objective, :ship, :captain, :primary_observer, :chief_scientist
        json.observations do 
          json.array! @observations do |observation|
            json.extract! observation, :observed_at, :latitude, :longitude, :uuid
            json.primary_observer observation.primary_observer.try(:name)
            json.additional_observers observation.additional_observers.map(&:name)
            json.ice do
              json.extract! observation.ice, :open_water_lookup_code, :thick_ice_lookup_code,
                     :thin_ice_lookup_code, :total_concentration
            end
            json.ice_observations do
              json.array! observation.ice_observations do |ice_observation|
                  json.extract! ice_observation, :obs_type, :partial_concentration, :algae_density_lookup_code,
                              :algae_location_lookup_code, :algae_lookup_code, :floe_size_lookup_code,
                              :ice_lookup_code, :sediment_lookup_code, :snow_lookup_code, :snow_thickness,
                              :thickness
                  json.topography ice_observation.topography, :concentration, :ridge_height,
                                :consolidated, :old, :snow_covered, :topography_lookup_code
                  json.melt_pond ice_observation.melt_pond, :bottom_type_lookup_code, :dried_ice,
                               :freeboard, :max_depth_lookup_code, :pattern_lookup_code, :rotten_ice,
                               :surface_coverage, :surface_lookup_code
              end
            
            end
            json.meteorology do
              json.extract! observation.meteorology, :air_pressure, :air_temperature,
                            :relative_humidity, :total_cloud_cover, :visibility_lookup_code, :water_temperature,
                            :weather_lookup_code, :wind_direction, :wind_speed
              json.clouds do
                json.array! observation.meteorology.clouds do |cloud|
                    json.extract! cloud, :cloud_type, :cloud_lookup_code, :cover, :height
                end
              end
            end
            json.notes observation.notes.map(&:text)
            json.ship observation.ship, :heading, :power, :ship_activity_lookup_code, :speed
            json.comments do
              json.array! observation.comments do  |comment|
                json.extract! comment, :text
                json.person comment.person.try(&:name)
              end
            end
            json.photos do
              json.array! observation.photos do |photo|
                json.extract! photo, :on_boat_location_lookup_code, :note, :checksum
                json.name photo.file_filename
              end
            end
          end
        end
    end.attributes!
    JSON.generate(result)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_observation
    @observation = Observation.where(id: params[:id]).includes(:ice_observations).first
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def observation_params
    params.require(:observation).permit(
      :cruise_id, :observed_at, :latitude, :longitude, :uuid,
      :lat_minutes, :lat_seconds, :lon_minutes, :lon_seconds,

app/helpers/observations_helper.rb
module ObservationsHelper
  def concentration_color(dominant_ice_type)
    case dominant_ice_type
    when 'old' then '#50BBD4'
    when 'new' then '#D9D9D9'
    when 'first_year' then '#BFD7D3'
    when 'other' then '#92A9C4'
    else '#FF0000'
    end
  end

  def concentration_options(max = nil)
    Ice::CONCENTRATION_VALUES.select { |i| (max.nil? || i.nil?) ? true : i <= max }.map { |i| [i, i] }
  end

  def ship_power_options
    Ship::POWER_VALUES.each_with_index.map { |x, i| [x, i] }
  end

  def cloud_cover_options
    Cloud::CLOUD_COVER_VALUES.map { |i| [i, i] }
  end

  def yes_no_options
    [['No', false], ['Yes', true]]
  end

  def dms(coordinate)
    coordinate = coordinate.to_f
    deg = coordinate < 0 ? coordinate.ceil : coordinate.floor

    min = ((coordinate - deg).abs * 60.0).floor
    sec = ((((coordinate - deg).abs * 60.0) % 1) * 60.0).round
    "DMS: #{deg} #{min} #{sec}"
  end

  def row_highlight(observation)
    if !observation.valid? && !observation.accepted?
      'danger'
    elsif observation.may_accept? && !assist?
      'warning'
    else
      ''
    end
  end
end

app/views/observations/_comments.html.haml
= render partial: 'observations/comments/comment', collection: @observation.comments

app/views/observations/_form.html.haml
= bootstrap_nested_form_for [@cruise,@observation], inline_errors: false do |f|
  = f.alert_message "This observation has the following errors:"

  .row
    .col-md-2.col-sm-3
      = link_to 'Add Comment', new_observation_comment_path(@observation),
        remote: true, class: 'btn btn-info btn-block'
      %br
      %ul#page.nav.nav-pills.nav-stacked
        %li.active= link_to "General", "#general-page", data: {toggle: 'tab'}
        %li= link_to "Ice", "#ice-page", data: {toggle: 'tab'}
        %li= link_to "Meteorology", "#meteorology-page", data: {toggle: 'tab'}
        %li= link_to "Photos", "#photos-page", data: {toggle: 'tab'}
        %li= link_to "Comments", "#comments-page", data: {toggle: 'tab'}
      %br
      = f.submit 'Save', class: 'btn btn-block btn-success'
      = f.submit 'Save and Exit', class: 'btn btn-block btn-warning'
      = link_to 'Exit without Saving', root_path,
                class: 'btn btn-block btn-danger',
                data: {confirm: 'Any changes made will be lost'}
    .col-md-10.col-sm-9
      .tab-content
        #general-page.tab-pane.active
          = render 'general', f: f
        #ice-page.tab-pane
          = render 'ice', f: f
        #meteorology-page.tab-pane
          = render 'meteorology', f: f
        #photos-page.tab-pane
          = render 'photo', f: f
        #comments-page.tab-pane
          = render 'comments', f: f

.row
  .col-md-12.footer

app/views/observations/_ice.html.haml
= f.fields_for :ice do |i|
  .row
    .col-md-6.col-sm-6
      = i.select :total_concentration, concentration_options,{ label: 'Total Concentration (tenths)', include_blank: 'No Observation'}
    .col-md-6.col-sm-6
      = i.collection_select :open_water_lookup_id, OpenWaterLookup.all, :id, :code_with_name,
        {label: 'Open Water', include_blank: 'No Observation'}
%ul.nav.nav-tabs.nav-justified
  %li.active= link_to "Ice", '#ice-tab', data: {toggle: 'tab'}
  %li= link_to "Snow", '#snow-tab', data: {toggle: 'tab'}
  %li= link_to "Topography", '#topography-tab', data: {toggle: 'tab'}
  %li= link_to "Melt", '#melt-tab', data: {toggle: 'tab'}
  %li= link_to "Other", '#other-tab', data: {toggle: 'tab'}
.tab-content
  #ice-tab.tab-pane.active
    = render partial: 'observations/ice/ice', locals: {f: f, ice_observation: @observation.primary_ice_observation}
    = render partial: 'observations/ice/ice', locals: {f: f, ice_observation: @observation.secondary_ice_observation}
    = render partial: 'observations/ice/ice', locals: {f: f, ice_observation: @observation.tertiary_ice_observation}
  #snow-tab.tab-pane
    = render partial: 'observations/ice/snow', locals: {f: f, ice_observation: @observation.primary_ice_observation}
    = render partial: 'observations/ice/snow', locals: {f: f, ice_observation: @observation.secondary_ice_observation}
    = render partial: 'observations/ice/snow', locals: {f: f, ice_observation: @observation.tertiary_ice_observation}
  #topography-tab.tab-pane
    = render partial: 'observations/ice/topography', locals: {f: f, ice_observation: @observation.primary_ice_observation}
    = render partial: 'observations/ice/topography', locals: {f: f, ice_observation: @observation.secondary_ice_observation}
    = render partial: 'observations/ice/topography', locals: {f: f, ice_observation: @observation.tertiary_ice_observation}
  #melt-tab.tab-pane
    = render partial: 'observations/ice/melt', locals: {f: f, ice_observation: @observation.primary_ice_observation}
    = render partial: 'observations/ice/melt', locals: {f: f, ice_observation: @observation.secondary_ice_observation}
    = render partial: 'observations/ice/melt', locals: {f: f, ice_observation: @observation.tertiary_ice_observation}
  #other-tab.tab-pane
    = render partial: 'observations/ice/other', locals: {f: f, ice_observation: @observation.primary_ice_observation}
    = render partial: 'observations/ice/other', locals: {f: f, ice_observation: @observation.secondary_ice_observation}
    = render partial: 'observations/ice/other', locals: {f: f, ice_observation: @observation.tertiary_ice_observation}
    = f.fields_for :ice do |i|
      .col-md-4.col-md-offset-2.col-sm-4.col-sm-offset-2
        = i.collection_select :thick_ice_lookup_id, IceLookup.all, :id, :code_with_name,
          {label: 'Thick Ice Type', include_blank: 'No Observation'}
      .col-md-4.col-sm-4
        = i.collection_select :thin_ice_lookup_id, IceLookup.all, :id, :code_with_name,
          {label: 'Thin Ice Type', include_blank: 'No Observation'}

app/views/observations/_meteorology.html.haml
%ul.nav.nav-tabs.nav-justified
  %li.active= link_to "Meteorology", '#meteorology-tab', data: {toggle: 'tab'}
  %li= link_to "Cloud", '#cloud-tab', data: {toggle: 'tab'}
.tab-content
  #meteorology-tab.tab-pane.active
    = render partial: 'observations/meteorology/meteorology', locals: {f: f}
  #cloud-tab.tab-pane
    = f.fields_for :meteorology do |m|
      = render partial: 'observations/meteorology/clouds', locals: {m: m, cloud: @observation.meteorology.high_cloud}
      = render partial: 'observations/meteorology/clouds', locals: {m: m, cloud: @observation.meteorology.medium_cloud}
      = render partial: 'observations/meteorology/clouds', locals: {m: m, cloud: @observation.meteorology.low_cloud}

app/views/observations/_observation.csv.erb
<%= observation.as_csv.to_csv.chomp.html_safe %>

app/views/observations/_observation.html+assist.haml
%tr.observation{class: row_highlight(observation)}
  %td= check_box_tag "observations[]", observation.id, false, id: "observation_#{observation.id}", class: 'export'
  %td= observation.observed_at
  %td= observation.updated_at
  %td= observation.ice.try(:total_concentration)
  %td= observation.primary_observer.try(&:name)
  %td= observation.additional_observers.map(&:name).join(",")
  %td
    = link_to edit_observation_path(observation), class: 'btn btn-xsm btn-default' do
      %i.fa.fa-edit
    = link_to observation_path(observation), method: :delete,
    data: {confirm: 'This will permanently remove this observation'},
    class: 'btn btn-xsm btn-danger' do
      %i.fa.fa-trash

app/views/observations/_observation.html.haml
%tr.observation{class: row_highlight(observation)}
  %td= observation.observed_at
  %td= observation.ice.try(:total_concentration)
  %td= observation.primary_observer.try(&:name)
  %td
    - if can? :edit, observation
      = link_to edit_observation_path(observation), class: 'btn btn-xsm btn-default' do
        %i.fa.fa-edit

app/views/observations/_photo.html.haml
= f.fields_for :photos do |f|
  .row
    .col-md-4.col-sm-4
      .fileinput{data: {provides: 'fileinput'}, class: (f.object.new_record? ? 'fileinput-new' : 'fileinput-exists')}
        .fileinput-new.thumbnail{style: 'width: 140px; height: 78px;', data: {trigger: 'fileinput'}}
        .fileinput-preview.thumbnail.fileinput-exists{style: 'max-width: 140px; max-height: 78px;'}
          = link_to image_tag(attachment_url(f.object, :file)), attachment_url(f.object, :file), target: '_blank' unless f.object.new_record?
        .btn.btn-default.btn-file{class: ('disabled' unless f.object.new_record?)}
          .fileinput-new Attach Photo
          .fileinput-exists.fileinput-filename
          = f.object.file_filename unless f.object.new_record?
          = f.attachment_field :file

    .col-md-3.col-sm-3
      = f.collection_select :on_boat_location_lookup_id, OnBoatLocationLookup.all, :id, :name,
        {label: 'Taken From', include_blank: 'Not Specified'}
    .col-md-3.col-sm-3
      = f.link_to_remove "Delete", class: 'btn btn-danger', style: 'margin-top: 25px'


= f.link_to_add "Add Additional Photo", :photos, class: 'btn btn-primary'

app/views/observations/aspect.csv.erb
<%= Observation.csv_headers %>
<%= render @observations %>

app/views/observations/aspect_csv.erb
<%= observation.to_s %>

app/views/observations/edit.html.haml
= render 'form'

app/views/observations/index.csv.erb
<%= Observation.csv_headers %>
<%= render @observations %>

app/views/observations/index.html.haml
%h1 Listing observations
%table
  %thead
    %tr
      %th Cruise
      %th Observed at
      %th Latitude
      %th Longitude
      %th Uuid
      %th{:colspan => "3"}
  %tbody
    - @observations.each do |observation|
      %tr
        %td= observation.cruise_id
        %td= observation.observed_at
        %td= observation.latitude
        %td= observation.longitude
        %td= observation.uuid
        %td= link_to 'Show', observation
        %td= link_to 'Edit', edit_observation_path(observation)
        %td= link_to 'Destroy', observation, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Observation', new_observation_path