config/routes.rb
Rails.application.routes.draw do
  resources :cruises do
      member do
        get :aspect, to: 'observations#aspect'
      end
    resources :observations, except: [:new], shallow: true do
      collection do
        
        post :import
        post :import_follow_up
        delete :all
        delete :unapproved
        delete :invalid
      end
      member do
        patch :approve
      end
      
      resources :photos, shallow: false
      resources :comments, except: [:index, :show], shallow: false
    end
    resources :charts, only: [:index] do
      get :total_concentration, on: :collection
      get :ice_type, on: :collection
    end
    post :approve, on: :member
    post :approve_observations, on: :member
    resources :uploaded_files, only: [:create, :new]
    resources :photos, only: [:index] do
      get :download
    end
  end
  resources :lookups, only: [:index, :show]

  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  get '/auth/:provider/disable', to: 'users#disable_provider'
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  resources :sessions
  resources :memberships
  get '/photos/*filename', to: 'photos#show', as: :photos

  resources :users

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'cruises#index'

end

app/models/concerns/importable/ice_observation.rb
module Importable
  module IceObservation
    extend ActiveSupport::Concern

    ASSIGNABLE_ATTRIBUTES = %w( obs_type
                                partial_concentration
                                algae_density_lookup_code
                                algae_location_lookup_code
                                algae_lookup_code
                                floe_size_lookup_code
                                ice_lookup_code
                                sediment_lookup_code
                                snow_thickness
                                snow_lookup_code
                                thickness
                                ).freeze

    ASSIGNABLE_MODELS = %w( topography melt_pond ).freeze

    def from_export(json)
      obs_data = json.dup

      assign_attributes(obs_data.select { |k, _v| ASSIGNABLE_ATTRIBUTES.include?(k) })

      ASSIGNABLE_MODELS.each do |model|
        next unless obs_data.key?(model)

        case
        when obs_data[model].is_a?(Hash)
          send("build_#{model}").from_export(obs_data[model])
        when obs_data[model].is_a?(Array)
          obs_data[model].each do |m|
            send(model).build.from_export(m)
          end
        end
      end
    end
  end
end

app/models/ice_observation.rb
class IceObservation < ActiveRecord::Base
  include Lookupable
  include Importable::IceObservation
  belongs_to :observation

  lookup :algae_lookup
  lookup :algae_density_lookup
  lookup :algae_location_lookup
  lookup :floe_size_lookup
  lookup :ice_lookup
  lookup :sediment_lookup
  lookup :snow_lookup

  has_one :melt_pond, dependent: :destroy
  has_one :topography, dependent: :destroy

  accepts_nested_attributes_for :melt_pond, :topography

  scope :primary, -> { where(obs_type: 'primary') }
  scope :secondary, -> { where(obs_type: 'secondary') }
  scope :tertiary, -> { where(obs_type: 'tertiary') }

  validates :obs_type, uniqueness: { scope: :observation_id }

  with_options allow_blank: true do |record|
    record.validates :partial_concentration, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
    record.validates :thickness,  numericality: { only_integer: true, greater_than_or_equal_to: 0 }
    record.validates :snow_thickness,  numericality: { only_integer: true, greater_than_or_equal_to: 0 }
    record.validates :obs_type, inclusion: { in: %w(primary secondary tertiary) }
    record.validates_with Validations::LookupCodeValidator, fields: {
      ice_lookup: 'ice_lookup',
      floe_size_lookup: 'floe_size_lookup',
      snow_lookup: 'snow_lookup',
      algae_lookup: 'algae_lookup',
      algae_density_lookup: 'algae_density_lookup',
      algae_location_lookup: 'algae_location_lookup',
      sediment_lookup: 'sediment_lookup' }
  end

  validate :ice_types_with_ten_codes_cant_have_floe_size

  def ice_type
    case ice_lookup.try(:code)
    when *IceLookup::OLD_ICE then 'old'
    when *IceLookup::NEW_ICE then 'new'
    when *IceLookup::FIRST_YEAR_ICE then 'first-year'
    when *IceLookup::OTHER then 'other'
    end
  end

  def as_csv
    [
      partial_concentration,
      ice_lookup.try(:code),
      thickness,
      floe_size_lookup.try(:code),
      snow_lookup.try(:code),
      snow_thickness,
      topography.as_csv,
      melt_pond.as_csv,
      algae_lookup.try(:code),
      sediment_lookup.try(:code),
      algae_density_lookup.try(:code),
      algae_location_lookup.try(:code)
    ]
  end

  private

  def ice_types_with_ten_codes_cant_have_floe_size
    return unless %w(Shuga Frazil Grease Slush).include?(ice_lookup.try(:name))
    return if floe_size_lookup.nil?

    errors.add(:ice_lookup_id, "#{ice_lookup.name} cannot have a floe size")
  end
end

app/controllers/ice_observations_controller.rb
class IceObservationsController < ApplicationController
  before_action :set_ice_observation, only: [:show, :edit, :update, :destroy]

  # GET /ice_observations
  # GET /ice_observations.json
  def index
    @ice_observations = IceObservation.all
  end

  # GET /ice_observations/1
  # GET /ice_observations/1.json
  def show
  end

  # GET /ice_observations/new
  def new
    @ice_observation = IceObservation.new
  end

  # GET /ice_observations/1/edit
  def edit
  end

  # POST /ice_observations
  # POST /ice_observations.json
  def create
    @ice_observation = IceObservation.new(ice_observation_params)

    respond_to do |format|
      if @ice_observation.save
        format.html { redirect_to @ice_observation, notice: 'Ice observation was successfully created.' }
        format.json { render :show, status: :created, location: @ice_observation }
      else
        format.html { render :new }
        format.json { render json: @ice_observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ice_observations/1
  # PATCH/PUT /ice_observations/1.json
  def update
    respond_to do |format|
      if @ice_observation.update(ice_observation_params)
        format.html { redirect_to @ice_observation, notice: 'Ice observation was successfully updated.' }
        format.json { render :show, status: :ok, location: @ice_observation }
      else
        format.html { render :edit }
        format.json { render json: @ice_observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ice_observations/1
  # DELETE /ice_observations/1.json
  def destroy
    @ice_observation.destroy
    respond_to do |format|
      format.html { redirect_to ice_observations_url, notice: 'Ice observation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ice_observation
    @ice_observation = IceObservation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ice_observation_params
    params.require(:ice_observation).permit(
      :observation_id, :floe_size_lookup_id, :snow_lookup_id, :ice_lookup_id,
      :algae_lookup_id, :algae_density_lookup_id, :algae_density_lookup_id,
      :sediment_lookup_id, :partial_concentration, :thickness, :snow_thickness,
      :obs_type
    )
  end
end

app/helpers/ice_observations_helper.rb
module IceObservationsHelper
  def ice_without_floe_size
    IceLookup.where(code: [10,11,12,13]).pluck(:id)
  end
end

app/views/ice_observations/_form.html.haml
= form_for(@ice_observation) do |f|
  - if @ice_observation.errors.any?
    #error_explanation
      %h2
        = pluralize(@ice_observation.errors.count, "error")
        prohibited this ice_observation from being saved:
      %ul
        - @ice_observation.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :observation_id
    %br/
    = f.number_field :observation_id
  .field
    = f.label :floe_size_lookup_id
    %br/
    = f.number_field :floe_size_lookup_id
  .field
    = f.label :snow_lookup_id
    %br/
    = f.number_field :snow_lookup_id
  .field
    = f.label :ice_lookup_id
    %br/
    = f.number_field :ice_lookup_id
  .field
    = f.label :algae_lookup_id
    %br/
    = f.number_field :algae_lookup_id
  .field
    = f.label :algae_density_lookup_id
    %br/
    = f.number_field :algae_density_lookup_id
  .field
    = f.label :algae_density_lookup_id
    %br/
    = f.number_field :algae_density_lookup_id
  .field
    = f.label :sediment_lookup_id
    %br/
    = f.number_field :sediment_lookup_id
  .field
    = f.label :partial_concentration
    %br/
    = f.number_field :partial_concentration
  .field
    = f.label :thickness
    %br/
    = f.number_field :thickness
  .field
    = f.label :snow_thickness
    %br/
    = f.number_field :snow_thickness
  .field
    = f.label :obs_type
    %br/
    = f.text_field :obs_type
  .actions
    = f.submit

app/views/ice_observations/edit.html.haml
%h1 Editing ice_observation
= render 'form'
= link_to 'Show', @ice_observation
|
\#{link_to 'Back', ice_observations_path}

app/views/ice_observations/index.html.haml
%h1 Listing ice_observations
%table
  %thead
    %tr
      %th Observation
      %th Floe size lookup
      %th Snow lookup
      %th Ice lookup
      %th Algae lookup
      %th Algae density lookup
      %th Algae density lookup
      %th Sediment lookup
      %th Partial concentration
      %th Thickness
      %th Snow thickness
      %th Obs type
      %th{:colspan => "3"}
  %tbody
    - @ice_observations.each do |ice_observation|
      %tr
        %td= ice_observation.observation_id
        %td= ice_observation.floe_size_lookup_id
        %td= ice_observation.snow_lookup_id
        %td= ice_observation.ice_lookup_id
        %td= ice_observation.algae_lookup_id
        %td= ice_observation.algae_density_lookup_id
        %td= ice_observation.algae_density_lookup_id
        %td= ice_observation.sediment_lookup_id
        %td= ice_observation.partial_concentration
        %td= ice_observation.thickness
        %td= ice_observation.snow_thickness
        %td= ice_observation.obs_type
        %td= link_to 'Show', ice_observation
        %td= link_to 'Edit', edit_ice_observation_path(ice_observation)
        %td= link_to 'Destroy', ice_observation, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Ice observation', new_ice_observation_path

app/views/ice_observations/new.html.haml
%h1 New ice_observation
= render 'form'
= link_to 'Back', ice_observations_path

app/views/ice_observations/show.html.haml
%p#notice= notice
%p
  %strong Observation:
  = @ice_observation.observation_id
%p
  %strong Floe size lookup:
  = @ice_observation.floe_size_lookup_id
%p
  %strong Snow lookup:
  = @ice_observation.snow_lookup_id
%p
  %strong Ice lookup:
  = @ice_observation.ice_lookup_id
%p
  %strong Algae lookup:
  = @ice_observation.algae_lookup_id
%p
  %strong Algae density lookup:
  = @ice_observation.algae_density_lookup_id
%p
  %strong Algae density lookup:
  = @ice_observation.algae_density_lookup_id
%p
  %strong Sediment lookup:
  = @ice_observation.sediment_lookup_id
%p
  %strong Partial concentration:
  = @ice_observation.partial_concentration
%p
  %strong Thickness:
  = @ice_observation.thickness
%p
  %strong Snow thickness:
  = @ice_observation.snow_thickness
%p
  %strong Obs type:
  = @ice_observation.obs_type
= link_to 'Edit', edit_ice_observation_path(@ice_observation)
|
\#{link_to 'Back', ice_observations_path}