config/routes.rb
Rails.application.routes.draw do
  resources :cruises do
      member do
        get :aspect, to: 'observations#aspect'
      end
    resources :observations, except: [:new], shallow: true do
      collection do
        
        post :import
        post :import_follow_up
        delete :all
        delete :unapproved
        delete :invalid
      end
      member do
        patch :approve
      end
      
      resources :photos, shallow: false
      resources :comments, except: [:index, :show], shallow: false
    end
    resources :charts, only: [:index] do
      get :total_concentration, on: :collection
      get :ice_type, on: :collection
    end
    post :approve, on: :member
    post :approve_observations, on: :member
    resources :uploaded_files, only: [:create, :new]
    resources :photos, only: [:index] do
      get :download
    end
  end
  resources :lookups, only: [:index, :show]

  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  get '/auth/:provider/disable', to: 'users#disable_provider'
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  resources :sessions
  resources :memberships
  get '/photos/*filename', to: 'photos#show', as: :photos

  resources :users

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'cruises#index'

end

app/controllers/cruises_controller.rb
class CruisesController < ApplicationController
  authorize_resource

  before_action :set_cruise, only: [:show, :edit, :update, :destroy, :approve, :reject]
  before_action :set_active_cruise, only: [:index, :show]
  before_action :set_observations, only: [:show]
  before_action :set_current_year, only: [:index]
  # respond_to :geojson, :json, :csv, :zip
  # GET /cruises
  # GET /cruises.json
  def index
    @cruises = Cruise.accessible_by(current_ability).for_year(@current_year).order(starts_at: :desc)
    @available_years = Cruise.accessible_by(current_ability).start_dates.group_by(&:year)
    if Rails.application.secrets.icewatch_assist && @cruises.empty?
      redirect_to new_cruise_path
    end
  end

  # GET /cruises/1
  # GET /cruises/1.json
  def show
    if @cruise.approved? or can?(:read, @cruise)
      respond_to do |format|
        format.html
        format.geojson
        #~ format.json
        #~ format.csv
        format.csv { send_data build_csv, filename: "cruise-metadata-#{@cruise.id}.csv"}
        format.json { send_data build_json, filename: "cruise-metadata-#{@cruise.id}.json"}
        format.zip do
          send_data File.read(@cruise.zip!(@observations, !!params[:photos]))
        end
      end
    else
      redirect_to root_url, alert: "You don't have access to that cruise"
    end
  end

  # GET /cruises/new
  def new
    @cruise = Cruise.new
  end

  # GET /cruises/1/edit
  def edit
  end

  # POST /cruises
  # POST /cruises.json
  def create
    @cruise = Cruise.new(cruise_params)
    unless current_user.new_record?
      @cruise.users = [current_user]
    end

    respond_to do |format|
      if @cruise.save
        format.html { redirect_to after_modify_path, notice: 'Cruise was successfully created.' }
        format.json { render :show, status: :created, location: @cruise }
        AdminMailer.new_cruise(@cruise, current_user).deliver
      else
        format.html { render :new }
        format.json { render json: @cruise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cruises/1
  # PATCH/PUT /cruises/1.json
  def update
    respond_to do |format|
      if @cruise.update_attributes(cruise_params)
        format.html { redirect_to after_modify_path, notice: 'Cruise was successfully updated.' }
        format.json { render :show, status: :ok, location: @cruise }
      else
        format.html { render :edit }
        format.json { render json: @cruise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cruises/1
  # DELETE /cruises/1.json
  def destroy
    @cruise.destroy
    respond_to do |format|
      format.html { redirect_to cruises_url, notice: 'Cruise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approve
    if @cruise.update_attribute(:approved, true)
      redirect_to cruise_path(@cruise), notice: 'Cruise has been approved'
    else
      redirect_to cruise_path(@cruise), error: 'Cruise could not be approved'
    end
  end

  def approve_observations
    @cruise = Cruise.find params[:id]
    # FIXME: should return counts of succes/failure, or some other useful information
    @cruise.batch_approve_observations(filter_invalid?)

    redirect_to @cruise, notice: "Approved all valid observations for #{@cruise}"
  end

  private
  
  def build_csv
     ## build csv metadata file
    template = "<%= Cruise.csv_headers %>
    <%= @cruise.as_csv.to_csv.chomp.html_safe %>
    "
    csv = ERB.new(template).result binding
  
  end
  
  
  def build_json
    result = Jbuilder.new do |json|
      json.extract! @cruise, :starts_at, :ends_at, :ship, :objective, :captain, :chief_scientist
      json.primary_observer @cruise.primary_observer.try(:name)
    end.attributes!
    JSON.generate(result)
  end
  
  
  def set_current_year
    year = params[:year] || Cruise.order(starts_at: :desc).first.try(:year)
    @current_year = year || Time.now.year
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_cruise
    @cruise = Cruise.find(params[:id])
  end

  def set_observations
    @observations = @cruise.observations.order(observed_at: :desc).accessible_by(current_ability)
    @observations = @observations.where(id: params[:observations].map(&:to_i)) if params[:observations]
    @observations = @observations.page(params[:page]) unless request.format == 'application/zip'
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cruise_params
    params.require(:cruise).permit(:starts_at, :ends_at, :objective, :approved,
                                   :chief_scientist, :captain, :ship,
                                   :primary_observer_id_or_name)
  end

  def set_active_cruise
    @active_cruise = Cruise.where(id: cookies[:current_cruise]).first || Cruise.first
  end

  def after_modify_path
    Rails.application.secrets.icewatch_assist ? root_path : @cruise
  end

  def filter_invalid?
    params[:filter_invalid] == 'false' ? false : true
  end
end

app/helpers/admin/cruises_helper.rb
module Admin::CruisesHelper
end

app/helpers/cruises_helper.rb
module CruisesHelper
  def active_cruise(cruise)
    @active_cruise == cruise ? 'list-group-item-info' : ''
  end

  def ymd(date)
    date.try(:strftime, '%Y-%m-%d') || nil
  end

  def cruise_highlight(cruise)
    cruise.approved? ? '' : 'list-group-item-warning'
  end

  def cruise_lock_state(cruise)
    cruise.locked? ? 'unlock' : 'lock'
  end

  def ogre_url
    Rails.application.secrets.ogre_url
  end

  def list_group_item_for(data, label)
    return if data.nil?
    content_tag(:li, '', class: 'list-group-item') do
      concat(content_tag(:strong, label))
      concat(data)
    end
  end

  def cruise_dates(cruise, format_str)
    s = cruise.starts_at.try(:strftime, format_str)
    e = cruise.ends_at.try(:strftime, format_str)
    "#{s} to #{e}"
  end
  
end

app/views/cruises/_cruise.csv.erb
<%= cruise.as_csv.to_csv.chomp.html_safe %>

app/views/cruises/_form.html.haml
= bootstrap_form_for @cruise do |f|
  %table.table.table-striped
    %tr
      %td= f.text_field :ship
      %td= f.text_field :captain
    %tr
      %td= f.date_field :starts_at, class: 'datetimepicker',
        data: {"date-pickTime" => false, "date-format" => 'YYYY-MM-DD'}
      %td= f.date_field :ends_at, class: 'datetimepicker',
        data: {"date-pickTime" => false, "date-format" => 'YYYY-MM-DD'}
    %tr
      %td= f.text_field :chief_scientist
      %td
        =f.collection_select :primary_observer_id_or_name, Person.all, :id, :name,
        {label: 'Primary Observer', include_blank: true}, class: 'person-field', placeholder: 'Select person or type to add'
        =# f.text_field :primary_observer_id_or_name, label: 'Primary Observer'
    %tr
      %td{colspan: 2}= f.text_area :objective
  - unless @cruise.new_record?
    = link_to root_path, class: 'btn btn-default' do
      %i.fa.fa-arrow-left
      Cancel
  = f.submit class: 'btn btn-primary'

app/views/cruises/_layer.html.haml
%layer{data: {url: cruise_path(layer, :geojson)}}

app/views/cruises/_observation.html+assist.haml
%tr.observation{class: row_highlight(observation)}
  %td= check_box_tag "observations[]", observation.id, false, id: "observation_#{observation.id}", class: 'export'
  %td= observation.observed_at
  %td= observation.updated_at
  %td= observation.ice.try(:total_concentration)
  %td= observation.primary_observer.try(&:name)
  %td= observation.additional_observers.map(&:name).join(",")
  %td
    = link_to edit_observation_path(observation), class: 'btn btn-xsm btn-default' do
      %i.fa.fa-edit
    = link_to observation_path(observation), method: :delete,
    data: {confirm: 'This will permanently remove this observation'},
    class: 'btn btn-xsm btn-danger' do
      %i.fa.fa-trash

app/views/cruises/_observation.html.haml
%tr.observation{class: row_highlight(observation)}
  %td= observation.observed_at
  %td= observation.latitude
  %td= observation.longitude
  %td= observation.ice.try(:total_concentration)
  %td= observation.primary_observer.try(&:name)
  %td
    - if can?(:manage, Observation) && !observation.accepted?
      .btn-group.pull-right
        - if observation.valid? && !observation.accepted?
          = link_to approve_observation_path(observation), class: 'btn btm-xsm btn-success', method: :patch do
            %i.fa.fa-thumbs-up
        = link_to edit_observation_path(observation), class: 'btn btn-xsm btn-default' do
          %i.fa.fa-edit
        = link_to observation_path(observation), method: :delete,
          data: {confirm: 'This will permanently remove this observation'},
          class: 'btn btn-xsm btn-danger' do
          %i.fa.fa-trash
    - if observation.photos.count > 0
      = link_to observation_photos_path(observation), class: 'btn btn-xsm btn-default' do
        %i.fa.fa-photo

app/views/cruises/_sidebar.html.haml
%ul.list-group#cruise-about
  %li.list-group-item.active
    %strong About
  = list_group_item_for(@cruise.captain, 'Captain: ')
  = list_group_item_for(@cruise.chief_scientist, 'Chief Scientist: ')
  = list_group_item_for(@cruise.primary_observer.try(:name), "Primary Observer: ")
  = list_group_item_for(@cruise.objective, "Objective: ")
  = list_group_item_for(@cruise.starts_at, "Cruise Start: ")
  = list_group_item_for(@cruise.ends_at, "Cruise Finish: ")

.panel.panel-default
  #map.map
    = render partial: 'cruises/layer', locals: { layer: @cruise }
  = render 'cruises/legend'

app/views/cruises/_sidebar_approve.html.haml
- if can?(:approve, Cruise) && !@cruise.approved?
  %li.list-group-item
    = link_to approve_cruise_path(@cruise), method: :post do
      %i.fa.fa-thumbs-up
      Approve Cruise

- if can?(:approve, Observation) && @cruise.approved?
  %li.list-group-item
    = link_to approve_observations_cruise_path(@cruise), method: :post do
      %i.fa.fa-thumbs-up
      Approve Valid Observations
  - if current_user.role == 'admin'
    %li.list-group-item.list-group-item-danger
      = link_to approve_observations_cruise_path(@cruise, filter_invalid: false), method: :post, data: {confirm: "This will approve ALL observations, including invalid ones. Please double check this is what you intend to do."} do
        %i.fa.fa-thumbs-up
        Approve All Observations

app/views/cruises/_sidebar_destroy.html.haml
- if can?(:destroy, Cruise)
  %li.list-group-item.list-group-item-danger
    = link_to cruise_path(@cruise), method: :delete, data: {confirm: 'Destroy this cruise and all associated observations?'} do
      %i.fa.fa-trash
      Destroy Cruise

app/views/cruises/_sidebar_lock.html.haml
- if can?(:lock, @cruise)
  - if @cruise.locked?
    %li.list-group-item
      = link_to cruise_path(@cruise) do
        %i.fa{class: "fa-#{cruise_lock_state}"}
        = "#{cruise_lock_state}.capitalize Cruise"

app/views/cruises/edit.html.haml
%h1= "Editing #{@cruise.ship}"
= render 'form'

app/views/cruises/index.html+assist.haml
.jumbotron
  %h3 Welcome to the
  %h2 Arctic Shipborne Sea Ice Standardization Tool
  = link_to "Start Observation", cruise_observations_path(@active_cruise), class: 'btn btn-primary btn-lg', method: 'POST'
.row
  .col-md-2.col-sm-2
    %ul.list-group
      %li.list-group-item.active
        Export without photos
      %li.list-group-item.list-group-item-info
        Use this when sending data from ship
      %li.list-group-item
        = link_to "All Observations", cruise_path(@active_cruise, :zip)
      %li.list-group-item
        = link_to "Selected Observations", cruise_path(@active_cruise, :zip), class: 'selected-export'
    %ul.list-group
      %li.list-group-item.active
        Export with photos
      %li.list-group-item.list-group-item-info
        It is recommended to not export with photos until returning to port and sufficient
        bandwidth is available.
      %li.list-group-item
        = link_to "All Observations", cruise_path(@active_cruise, :zip, photos: true)
      %li.list-group-item
        = link_to "Selected Observations", cruise_path(@active_cruise, :zip, photos: true), class: 'selected-export'

    %ul.list-group
      %li.list-group-item.active
        View Cruise as
      %li.list-group-item
        = link_to "CSV", cruise_path(@active_cruise, :csv)
      %li.list-group-item
        = link_to "JSON", cruise_path(@active_cruise, :json)

    %ul.list-group
      %li.list-group-item.active
        Import
      %li.list-group-item.cruise-upload{data: {provides: 'fileinput'}}
        = link_to "From CSV", '#', data: {trigger: 'fileinput'}
        = file_field_tag 'observations', data: {'submit-url' => import_cruise_observations_path(@active_cruise)},
          class: 'hidden'

    %ul.list-group
      %li.list-group-item.active
        Cruise
      %li.list-group-item
        = link_to "Edit", edit_cruise_path(@active_cruise)

    %ul.list-group
      %li.list-group-item.active.danger Delete
      %li.list-group-item.list-group-item-danger
        = link_to all_cruise_observations_path(@active_cruise), method: :delete, data: {confirm: 'This will permanetly destroy all observations, are you sure?'} do
          %i.fa.fa-trash
          All Observations

  .col-md-10.col-sm-10
    .panel.panel-primary
      .panel-heading
        %h4
          = "#{@active_cruise.ship}: #{@active_cruise.starts_at} - #{@active_cruise.ends_at}"
      = render 'cruise_observations', cruise: @active_cruise

app/views/cruises/index.html.haml
.row
  .col-md-3
    %ul.list-group
      %li.list-group-item
        = link_to 'Guide to collecting and uploading data', page_path('data_guide')
      %li.list-group-item
        = link_to 'Download ASSIST', page_path('assist')
      - if can? :create, Cruise
        %li.list-group-item
          = link_to "Register Cruise", new_cruise_path
    %ul.list-group
      %li.list-group-item.active
        %strong= "#{@current_year} Cruises"
      - @cruises.each do |cruise|
        %li.list-group-item{class: cruise_highlight(cruise)}
          = link_to cruise.ship, cruise_path(cruise)
          %span.badge
            = cruise.observations.accessible_by(current_ability).count
          %small= cruise_dates(cruise, '%b %d')
    %ul.list-group
      %li.list-group-item.active
        %strong Available Years
      - @available_years.each do |year, cruises|
        %li.list-group-item
          = link_to year, cruises_path(year: year)
          %span.badge
            = cruises.count
  .col-md-9
    .panel.panel-default
      #map.map
        = render partial: 'layer', collection: @cruises
      = render 'legend'

    -# = render 'map', cruise_info: cruises_path('geojson', year: @current_year)

app/views/cruises/new.html.haml
%h1 New cruise
= render 'form'

app/views/cruises/show.csv.erb
<%= Cruise.csv_headers %>
<%= render @cruise %>